name: Build

on:
    pull_request:
        paths-ignore:
            - 'README.md'
    push:
        branches:
            - main

env:
    LC_APPLICATION_ID: cargo-pants

jobs:
    build:
        runs-on: ubuntu-latest
        container: rust:1.84
        steps:
            - uses: actions/checkout@v6

            - name: Version information
              run: rustc --version; cargo --version; rustup --version

            - name: Calculate dependencies
              run: cargo generate-lockfile

            - name: Setup Rust cache
              uses: Swatinem/rust-cache@v2
              with:
                  workspaces: .

            - name: Install rustfmt
              run: rustup component add rustfmt

            - name: Check formatting
              run: cargo fmt -- --check

            - name: Build all targets
              run: cargo build --all --all-targets

            - name: Run all tests
              run: cargo test --all

            - name: Dogfood with locally built Cargo Pants
              run: ./target/debug/cargo-pants pants --ignore-file .pants-ignore

            - name: Install Cargo Pants as Cargo Subcommand
              run: cargo install cargo-pants --force --path ./

            - name: Dogfood Cargo Pants
              run: cargo pants

    sonatype:
        name: Sonatype Lifecycle
        runs-on: ubuntu-latest
        timeout-minutes: 5
        steps:
            - name: Checkout Code
              uses: actions/checkout@v6

            - name: Sonatype Lifecycle Evaluation
              id: evaluate
              uses: sonatype/actions/evaluate@v1
              with:
                  iq-server-url: ${{ vars.SONATYPE_PLATFORM_URL }}
                  username: ${{ secrets.SONATYPE_LIFECYCLE_USERNAME }}
                  password: ${{ secrets.SONATYPE_LIFECYCLE_PASSWORD }}
                  application-id: ${{ env.LC_APPLICATION_ID }}
                  scan-targets: 'Cargo.lock'
